### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by karelbilek** [bitcoin/bitcoin-detached-sigs#18]
I have found reference to this repo here

https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#next-steps

But it seems nothing lives here... is all moved to https://github.com/bitcoin-core/gitian.sigs ?

**Comment by hebasto** [comment]
https://github.com/bitcoin-core/bitcoin-detached-sigs/tree/0.17

**Comment by karelbilek** [comment]
Oooooh I missed that. Sorry!
